sainik-khaddar/CodeHUB

indianflag.cpp
=> Added Indian Flag C++ code

10-regular-expression-matching/README.md, 10-regular-expression-matching/regular-expression-matching.py
Added Q.10 of Leetcode, coded in Python3. The question is Regular Expression Matching, and it is a Hard problem. It is solved using Dynamic Programming.
I have also added the Read Me file.
=> Added Q.10 of Leetcode, coded in Python3. Time: 33ms, Space: 14.2 MB

23-Merge-k-Sorted-Lists/23-Merge-k-Sorted-Lists.cpp, 23-Merge-k-Sorted-Lists/README.md
61 ms, faster than 35.51% of C++ online submissions
=> Added 23. Merge k Sorted Lists

README.md
This is the fixed ReadMe. Please assign it.
=> ReadMe Fixed

2410-Maximum Matching of Players With Trainers/Readme.md, 2410-Maximum Matching of Players With Trainers/program
Hey @sainik-khaddar can you please add my solution to your repository and label it as hactoberfesr
=> Added solution to 2410. Maximum Matching of Players With Trainers

Minimum Time to Make Rope Colorful.cpp, Number of Common Factors.cpp
@sainik-khaddar Can u add it ?
=> Create Minimum Time to Make Rope Colorful.cpp

1964_Largest-Number-After-Mutating-Substring/numberaftermutating, 1964_Largest-Number-After-Mutating-Substring/readme.md
Created a readme file for 1946. Largest Number After Mutating Substring and added code as well
=> Added For 1946. Largest Number After Mutating Substring

99-recover-binary-search-tree/99-recover-binary-search-tree.py, 99-recover-binary-search-tree/README.md, README.md
Q.99 - Recover Binary Search Tree
Coded in Python3. Also added Readme.md file
O(1) Space solution
=> Added Q-99 Leetcode, Recover Binary Search Tree in Python

Partition Equal Subset Sum.cpp
Code written using concept of DP(Dynamic Programming)
=> Create Partition Equal Subset Sum.cpp

210-Course Schedule II
Please merge it 
It isn't present in your repo
=> 210-Course Schedule II

Decode Ways.cpp, String to int.cpp
Code written Using Concept of DP
=> Create Decode Ways.cpp

2119. A Number After a Double Reversal.cpp
Reversing an integer means to reverse all its digits.
For example, reversing 2021 gives 1202. Reversing 12300 gives 321 as the leading zeros are not retained. Given an integer num, reverse num to get reversed1, then reverse reversed1 to get reversed2. Return true if reversed2 equals num. Otherwise return false.
Example 1:
Input: num = 526
Output: true
Explanation: Reverse num to get 625, then reverse 625 to get 526, which equals num.
Example 2:
Input: num = 1800
Output: false
Explanation: Reverse num to get 81, then reverse 81 to get 18, which does not equal num.
Example 3:
Input: num = 0
Output: true
Explanation: Reverse num to get 0, then reverse 0 to get 0, which equals num.
=> Create 2119. A Number After a Double Reversal.cpp

1512. Number of Good Pairs
Given an array of integers nums, return the number of good pairs.
A pair (i, j) is called good if nums[i] == nums[j] and i < j.
Example 1:
Input: nums = [1,2,3,1,1,3]
Output: 4
Explanation: There are 4 good pairs (0,3), (0,4), (3,4), (2,5) 0-indexed.
Example 2:
Input: nums = [1,1,1,1]
Output: 6
Explanation: Each pair in the array are good.
Example 3:
Input: nums = [1,2,3]
Output: 0
=> Create 1512. Number of Good Pairs

2426-Number of Pairs Satisfying Enequality
@sainik-khaddar Please merge this commit and add the label of hacktoberfest.
=> Added Solution for 2426 || Interview Ques

find all People With Secret/code.cpp, find all People With Secret/readme.md
please merge this pr @sainik-Khaddar
=> leetcode 2092 hard

2011. Final Value of Variable After Performing Operations.cpp
There is a programming language with only four operations and one variable X:
++X and X++ increments the value of the variable X by 1. --X and X-- decrements the value of the variable X by 1. Initially, the value of X is 0.
Given an array of strings operations containing a list of operations, return the final value of X after performing all the operations.
Example 1:
Input: operations = ["--X","X++","X++"]
Output: 1
Explanation: The operations are performed as follows: Initially, X = 0.
--X: X is decremented by 1, X =  0 - 1 = -1.
X++: X is incremented by 1, X = -1 + 1 =  0.
X++: X is incremented by 1, X =  0 + 1 =  1.
Example 2:
Input: operations = ["++X","++X","X++"]
Output: 3
Explanation: The operations are performed as follows: Initially, X = 0.
++X: X is incremented by 1, X = 0 + 1 = …
=> Create 2011. Final Value of Variable After Performing Operations.cpp

455-assign-cookies/455-assign-cookies.java, 455-assign-cookies/README.md
I have added the solution for 455-assign-cookies, kindly consider it.
=> Added 455-assign-cookies

52-N-Queens-II.cpp
Please merge my pull request for hacktoberfest 2022
=> 52-N-Queens-II.cpp

39-combination-sum/39-combination-sum.cpp, 39-combination-sum/Notes.md
leetcode 39-combination-sum probleam
=> added 39-combination-sum probleam

Top_K_Frequent_Elements.cpp
This is my solution for the problem Top K Frequent Elements on Leetcode.
=> Top_K_Frequent_Elements.cpp

4-Median of Two Sorted Arrays/Median of Two Sorted Arrays.java, 4-Median of Two Sorted Arrays/README.md
I have added Leetcode question kindly review and merge my PR.
=> Added leetcode solutions.

42-trapping-rain-water./ReadMe.md, 42-trapping-rain-water./trapping-rainwater.cpp
I added the code for trapping rain water. Please merge it @sainik-khaddar
=> Trapping rain water

Find_substring_with_given_value.js
@sainik-khaddar for the issue i raised
=> pr#3 for the issue i created

283. Move Zeroes/283. Move Zeroes.java
Added two different approaches
=> Added two different approaches

2390. Removing Stars From a String/Removing-Stars-From-a-String.cpp
Problem: Removing Stars From a String
Time Complexity: O(N)
Space Complexity: O(N)
Topics: Stack, String
=> Add Solution for Removing Stars From a String

Intersection of Two Linked Lists (Leetcode-160), Maximum Points You Can Obtain from Cards (Leetcode - 1423)
Intersection of Two Linked Lists (Leetcode-160)
=> Added  (Leetcode-160)

87 Scramble String/Scramble_String.py
Runtime: 65 ms
Problem :- 87(Hard) - Leetcode
=> 87_ScrambleString.py

218-The-Skyline-Problem.cpp
Please merge my pull request for hacktoberfest 2022.
=> 218-The-Skyline-Problem.cpp

1285C-Fadi and LCM/1285C.cpp, 1350B-Orac and Models/1350B.cpp, 1375C-Element Extermination/1375C.cpp, 1624D-Palindromes Coloring/1624D.cpp, 1709A-Three Doors/1709A.cpp, 1709B-Also Try Minecraft/1709B.cpp, 1709D-Rorororobot/1709D.cpp, 1711A-Perfect Permutation/1711A.cpp, 1711B-Party/1711B.cpp, 2SUM/2SUM.cpp
=> Some Codeforces Solutions

2416- Sum of prefix score of String
@sainik-khaddar Please merge this code for Problem 2416. And assign this as hacktoberfest accepted label.
=> Create 2416- Sum of prefix score of String

542- 01 Matrix.cpp
Added Accepted C++ Leetcode solution 542
=> this commit fixes #108

(Leetcode - 1423) Maximum Points You Can Obtain from Cards
Maximum Points You Can Obtain from Cards (Leetcode - 1423)
Issue no. #64
=> Added Leetcode-1423

975-ODD EVEN JUMP SOLUTION.cpp.txt, READ.md.txt
PLEASE ADD MY FILE TO YOUR REPOSITORY.
=> HACKTOBERFEST-2022

2414- Length of the Longest Alphabetical Continuous Substring.cpp, 860 - Lemonade change.cpp
Added accepted leetcode solution in C++
=> Hacktoberfest code2

2414- Length of the Longest Alphabetical Continuous Substring.cpp, 860 - Lemonade change.cpp
Added accepted leetcode solution in C++
=>  this commit fixes #121 

90-Subsets-II/90-subsets-II.cpp, 90-Subsets-II/notes.md
the second PR added 90-subsetsII problem
=> added 90-subsetsII problem

LCA_BST.cpp
Given a binary search tree and data of two nodes, find 'LCA' (Lowest Common Ancestor) of the given two nodes in the BST.
LCA
LCA of two nodes A and B is the lowest or deepest node which has both A and B as its descendants.
=> Function for LCA of Binary Search Tree Code is added
